# Site settings
title: AM Documentation Site 
email: davidxkohn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Documentation for the AM Project.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://davidkohn.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: davidkohn

# Build settings
markdown: kramdown
